services:
  # Main application server
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test runner
  test:
    build: .
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./tests:/app/tests
    command: uv run pytest tests/ -v
    depends_on:
      app:
        condition: service_healthy